version: '3.7'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=MIIOT
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=1234
    restart: always

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
    restart: always

  telegraf:
    build: ./telegraf
    container_name: telegraf
    depends_on:
      - influxdb
      - mqtt
    restart: always

  mqtt:
    build: ./mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto-config:/mosquitto/config
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always
